name: Docker MusicAPI CI
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
     - name: Check out the repo
       uses: actions/checkout@v3
     - name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build API image
       run: | 
          docker build --platform linux --tag camilopr11/musicapi:latest -f Dockerfile .
     - name: Publish API image
       run: |
          docker push camilopr11/musicapi:latest
     - name: App service auth
       uses: azure/webapps-deploy@v2
       with:
         app-name: 'musicapidev'
         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
         images: 'camilopr11/musicapi:latest'
