name: MusicAPI PROD
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
     - name: Check out the repo
       uses: actions/checkout@v3
     - name: Install dependencies
       run: npm install
     - name: Run Jest tests
       run: npm run test
     - name: Build if tests pass
       if: success()
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build API image
       run: | 
          docker build --platform linux --tag camilopr11/musicapi:prod -f Dockerfile .
     - name: Publish API image
       run: |
          docker push camilopr11/musicapi:prod
     - name: App service auth
       uses: azure/webapps-deploy@v2
       with:
         app-name: 'musicapiprod'
         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
         images: 'camilopr11/musicapi:prod'