name: MusicAPI PROD
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: MusicAPI build and deployment
    runs-on: ubuntu-latest
    steps:
     - name: Check out the repo
       uses: actions/checkout@v3
     - name: Install dependencies
       run: npm install
     - name: DockerHub login
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build API image
       run: | 
          docker build --platform linux --tag camilopr11/musicapi:prod -f Dockerfile .
     - name: Publish API image
       run: |
          docker push camilopr11/musicapi:prod
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: 1.8.4
     - name: Terraform init
       run: |
         terraform init
     - name: Terraform apply
       run: |
         terraform apply -auto-approve